#!/bin/sh

set -e

mkdir -p /mnt/php/etc /mnt/php/lib /mnt/ngx/log /mnt/ngx/etc

if [ ! -f /mnt/php/etc/php-fpm.conf ]; then
    rm -rf /mnt/php/etc/* /mnt/php/lib/*
    cp -r /tmp/etc/* /mnt/php/etc/
    cp -r /tmp/lib/* /mnt/php/lib/
    mv /mnt/php/etc/php-fpm.conf.default /mnt/php/etc/php-fpm.conf
fi

rm -rf $PHP_HOME/etc $PHP_HOME/lib/php/extensions/debug-non-zts-20151012
ln -s /mnt/php/etc $PHP_HOME/etc
ln -s /mnt/php/lib $PHP_HOME/lib/php/extensions/debug-non-zts-20151012

if [ ! -f /mnt/ngx/etc/nginx.conf ]; then
    cp -r /tmp/etc/*  /mnt/ngx/etc/
fi

php-fpm -c /mnt/php/etc/php.ini -y /mnt/php/etc/php-fpm.conf
exec "$@"
