#!/bin/sh

set -e

if [ "${1:0:1}" = '-' ]; then
	set -- nexus "$@"
fi

if [ ! -d $NEXUS_DATA/etc ]; then
    mv $NEXUS_HOME/etc $NEXUS_DATA/
		ln -s $NEXUS_DATA/etc $NEXUS_HOME/etc
fi

# mkdir -p $NEXUS_DATA/tmp $NEXUS_DATA/log
chown -R $NEXUS_GROUP:$NEXUS_USER $NEXUS_DATA

if [ "$1" = './bin/nexus' -a "$(id -u)" = '0' ]; then
	exec gosu $NEXUS_USER "$@"
else
  exec "$@"
fi
