#!/bin/sh

set -e

for path in conf logs; do \

  if [ ! -d $MYCOLLAB_DATA/$path ]; then
    mkdir -p $MYCOLLAB_DATA/$path; \
    mv /tmp/$path/* $MYCOLLAB_DATA/$path/;
  fi

  ln -s $MYCOLLAB_DATA/$path $MYCOLLAB_HOME/$path; \
done

chown -R $MYCOLLAB_GROUP:$MYCOLLAB_USER $MYCOLLAB_DATA

if [ "${1:0:1}" = '-' ]; then
	set -- startup.sh "$@"
fi

# Better OS/400 detection: see Bugzilla 31132
os400=false
case "`uname`" in
OS400*) os400=true;;
esac

# resolve links - $0 may be a softlink
PRG="$0"

while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

PRGDIR=`dirname "$PRG"`
EXECUTABLE=mycollab.sh

# Check that target executable exists
if $os400; then
  # -x will Only work on the os400 if the files are:
  # 1. owned by the user
  # 2. owned by the PRIMARY group of the user
  # this will not work if the user belongs in secondary groups
  eval
else
  if [ ! -x "$PRGDIR"/"$EXECUTABLE" ]; then
    echo "Cannot find $PRGDIR/$EXECUTABLE"
    echo "The file is absent or does not have execute permission"
    echo "This file is needed to run this program"
    exit 1
  fi
fi

if [ "$1" = 'startup' -a "$(id -u)" = '0' ]; then
  shift
	exec gosu $MYCOLLAB_USER "$PRGDIR"/"$EXECUTABLE" --start "$@"
else
  exec "$@"
fi
