#!/bin/sh

set -e

if [ ! -d $ELASTICSEARCH_DATA/config ]; then
    for path in config plugins data logs; \
        do \
            mkdir -p $ELASTICSEARCH_DATA/$path; \
            ln -s $ELASTICSEARCH_DATA/$path $ELASTICSEARCH_HOME/$path; \
        done

    mv /tmp/elasticsearch/config/* $ELASTICSEARCH_DATA/config/
    mkdir $ELASTICSEARCH_DATA/config/scripts
    chown -R $ELASTICSEARCH_GROUP:$ELASTICSEARCH_USER $ELASTICSEARCH_DATA
fi

if [ "${1:0:1}" = '-' ]; then
	set -- elasticsearch "$@"
fi

if [ "$1" = 'elasticsearch' -a "$(id -u)" = '0' ]; then
	exec gosu $ELASTICSEARCH_USER "$@"
else
    exec "$@"
fi