#+++++++++++++++++++++++++++++++++#
# Idea Docker container in Alpine #
#+++++++++++++++++++++++++++++++++#

FROM alpine
LABEL vendor=SoGlad
MAINTAINER Palm Tale<palmtale@glad.so>

ADD ideals /usr/local/bin/
EXPOSE 41017
CMD ["ideals"]