#+++++++++++++++++++++++++++++++++#
# Idea Docker container in Alpine #
#+++++++++++++++++++++++++++++++++#

FROM alpine
LABEL vendor=Glad.so
MAINTAINER Excepts <excepts@glad.so>

ADD ideals /usr/local/bin/
EXPOSE 41017
CMD ["ideals"]