#+++++++++++++++++++++++++++++++++#
# Idea Docker container in Alpine #
#+++++++++++++++++++++++++++++++++#

FROM alpine
LABEL vendor=Featx
MAINTAINER Excepts <excepts@aliyun.com>

ADD ideals /usr/local/bin/
EXPOSE 41017
CMD ["ideals"]