#+++++++++++++++++++++++++++++++++++++++#
#   Mongo Docker container in Alpine    #
#+++++++++++++++++++++++++++++++++++++++#

FROM alpine
LABEL vendor=Glad.so
MAINTAINER palmtale<palmtale@glad.so>

ENV GOSU_VERSION=1.10

RUN set -ex \
  && apk add -U gnupg wget mongodb ca-certificates \
  && cp -r /etc/conf.d /tmp/ \

  # Grab gosu for easy step-down from root
  && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64" \
  && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64.asc" \
  && export GNUPGHOME="$(mktemp -d)" \
  && gpg --keyserver pgp.mit.edu --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
  && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
  && chmod +x /usr/local/bin/gosu \
  && gosu nobody true \
  && apk del gnupg wget ca-certificates \
  && rm -rf /var/cache/apk/* $GNUPGHOME /usr/local/bin/gosu.asc \
  && echo -e '#!/bin/sh\n\
\n\
set -e\n\
\n\
mkdir -p /mnt/etc /mnt/log /mnt/db\n\
\n\
if [ ! -d /mnt/etc ]; then\n\
    mkdir -p /mnt/etc/\n\
    cp -r /tmp/conf.d/* /mnt/etc/\n\
fi\n\
\n\
rm -rf /etc/conf.d/mongodb /etc/conf.d/mongos\n\
ln -s /mnt/etc/mongodb /etc/conf.d/mongodb\n\
ln -s /mnt/etc/mongos /etc/conf.d/mongos\n\
\n\
if [ "${1:0:1}" = '-' ]; then\n\
	set -- mongod "$@"\n\
fi\n\
\n\
if [ "$1" = 'mongod' -a "$(id -u)" = '0' ]; then\n\
	chown -R mongodb /mnt\n\
	exec gosu mongodb "$@"\n\
else\n\
    exec "$@"\n\
fi\n\' >> /usr/bin/entry \
  && chmod u+x /usr/bin/entry 

EXPOSE 27017
ENTRYPOINT ["entry"]
CMD ["mongod", "--config", "/mnt/etc/mongod.conf"]