#!/bin/sh

set -e

if [ "${1:0:1}" = '-' ]; then
    set -- mongod "$@"
fi

if [ "$1" = 'mongod' -a "$(id -u)" = '0' ]; then
    chown -R mongodb /mnt
    exec gosu mongodb "$@"
else
    exec "$@"
fi
