#++++++++++++++++++++++++++++++++++#
# HHVM Docker container in CentOS  #
#++++++++++++++++++++++++++++++++++#

FROM centos:7.3.1611
LABEL vendor=Glad.so
MAINTAINER palmtale<m@glad.so>

ENV HHVM_HOME=/usr/local \
    HHVM_VERSION=3.19.1 \
    