#+++++++++++++++++++++++++++++++++#
# HHVM Docker container in Alpine #
#+++++++++++++++++++++++++++++++++#

FROM alpine
LABEL vendor=Featx
MAINTAINER Excepts <excepts@featx.org>

ARG HHVM_HOME=/usr/local
ARG HHVM_VERSION=3.19.1