#+++++++++++++++++++++++++++++++++++++#
#   Rust Docker container in Alpine   #
#+++++++++++++++++++++++++++++++++++++#

FROM alpine
LABEL vendor=Glad.so
MAINTAINER palmtale<palmtale@glad.so>

RUN set -ex \
  && apk add -U rust \

  && echo -e '#!/bin/sh\n\
\n\
set -e\n\
\n\
mkdir -p /mnt/etc /mnt/log /mnt/db\n\
\n\
if [ ! -d /mnt/etc/conf.d ]; then\n\
    mkdir -p /mnt/etc/conf.d/\n\
    cp -r /tmp/conf.d/* /mnt/etc/conf.d/\n\
fi\n\
\n\
if [ "${1:0:1}" = '-' ]; then\n\
	set -- "$@"\n\
fi\n\
\n\
if [ "$1" = 'mongod' -a "$(id -u)" = '0' ]; then\n\
	chown -R mongodb /mnt\n\
fi\n\
\n\	
exec "$@"' >> /usr/bin/entry \
  && chmod u+x /usr/bin/entry 

ENTRYPOINT ["entry"]
CMD [""]