#++++++++++++++++++++++++++++++++++++++#
#  Mariadb Docker container in Alpine  #
#++++++++++++++++++++++++++++++++++++++#

FROM alpine
LABEL vendor=Featx
MAINTAINER Excepts <excepts@aliyun.com>

RUN set -ex \
  && apk add -U mariadb \
  && cp -r /etc/conf.d /tmp/ \
  && echo -e '#!/bin/sh\n\
\n\
set -e\n\
\n\
mkdir -p /mnt/etc /mnt/log /mnt/db\n\
\n\
if [ ! -d /mnt/etc/conf.d ]; then\n\
    mkdir -p /mnt/etc/conf.d/\n\
    cp -r /tmp/conf.d/* /mnt/etc/conf.d/\n\
fi\n\
\n\
rm -rf /etc/conf.d/mongodb /etc/conf.d/mongos\n\
ln -s /mnt/etc/conf.d/mongodb /etc/conf.d/mongodb\n\
ln -s /mnt/etc/conf.d/mongos /etc/conf.d/mongos\n\
\n\
if [ "${1:0:1}" = '-' ]; then\n\
	set -- mongod "$@"\n\
fi\n\
\n\
if [ "$1" = 'mongod' -a "$(id -u)" = '0' ]; then\n\
	chown -R mongodb /mnt\n\
fi\n\
\n\	
exec "$@"' >> /usr/bin/entry \
  && chmod u+x /usr/bin/entry 

EXPOSE 27017
ENTRYPOINT ["entry"]
CMD ["mongod"]