#!/bin/sh

set -e

if [ "${1:0:1}" = '-' ]; then
	set -- $PG_USER "$@"
fi

mkdir -p $PG_DATA

# Init
if [ ! -d $PG_DATA/etc ]; then
	cp -r /tmp/* $PG_DATA/
	mkdir -p $PG_DATA/etc $PG_DATA/log $PG_DATA/data
	chmod 700 $PG_DATA
  chown -R $PG_GROUP:$PG_USER $PG_HOME
	chown -R $PG_GROUP:$PG_USER $PG_DATA

	eval "gosu $PG_USER initdb -D $PG_DATA/data"

	if [ "$POSTGRES_PASSWORD" ]; then
		pass="PASSWORD '$POSTGRES_PASSWORD'"
		authMethod=md5
	else
		cat >&2 <<-'EOWARN'
			****************************************************
			WARNING: No password has been set for the database.
							 This will allow anyone with access to the
							 Postgres port to access your database. In
							 Docker's default configuration, this is
							 effectively any other container on the same
							 system.
							 Use "-e POSTGRES_PASSWORD=password" to set
							 it in "docker run".
			****************************************************
		EOWARN

		pass=
		authMethod=trust
	fi

	{ echo; echo "host all all 0.0.0.0/0 $authMethod"; } >> "$PG_DATA/etc/pg_hba.conf"

	gosu $PG_USER pg_ctl -D $PG_DATA/data \
	  -l $PG_DATA/log/logfile \
		-o "-c listen_addresses='localhost'" \
		-w start

	gosu $PG_USER pg_ctl -D "$PG_DATA/data" \
	  -m fast \
		-w stop

	echo
	echo 'PostgreSQL init process complete; ready for start up.'
	echo
fi

# Run
if [ "$1" = 'postgres' ]; then
	exec gosu $PG_USER "$@"
else
  exec "$@"
fi
