#!/bin/sh

set -e

for path in etc lib; do \

  if [ ! -d $PHP_DATA/$path ]; then
    mkdir -p $PHP_DATA/$path; \
    cp -r /tmp/$path/* $PHP_DATA/$path/;
  fi
 \
done

if [ ! -f $PHP_DATA/etc/php-fpm.conf ]; then
    mv $PHP_DATA/etc/php-fpm.conf.default $PHP_DATA/etc/php-fpm.conf
fi

chown -R $PHP_GROUP:$PHP_USER $PHP_DATA

rm -rf $PHP_HOME/etc $PHP_HOME/lib/php/extensions/$PHP_EXT
ln -s $PHP_DATA/etc $PHP_HOME/etc
ln -s $PHP_DATA/lib $PHP_HOME/lib/php/extensions/$PHP_EXT

exec "$@"
